/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.*;
/**
 *
 * @author Minim
 */
public class BadConsequenceView extends javax.swing.JPanel {
    private BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    public void setBadConsequence(BadConsequence b){
        badConsequenceModel = b;
        text.setText(badConsequenceModel.getText());
        niveles.setText(Integer.toString(badConsequenceModel.getLevels()));
        
        if (badConsequenceModel.getClass() == NumericBadConsequence.class){
             ocultos.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getnHiddenTreasures()));
             visibles.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getnVisibleTreasures()));
        }
        else{
            ocultos.setText("0");
            visibles.setText("0");
        }
        
        if (badConsequenceModel.getClass() == SpecificBadConsequence.class){
            String svt = "";
            
            for (TreasureKind tk : ((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures()){
                svt += tk.toString();
            }
            
            visibles.setText(svt);
            
            String sht = "";
            
            for (TreasureKind tk : ((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures()){
                sht += tk.toString();
            }
             
            ocultos.setText(sht);
        }
        else{
            visibles.setText("empty");
            ocultos.setText("empty");
        }
       
        repaint();
        revalidate();
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        niveles = new javax.swing.JLabel();
        visibles = new javax.swing.JLabel();
        ocultos = new javax.swing.JLabel();
        text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel1.setText("MAL ROLLO");

        jLabel2.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel2.setText("Niveles");

        jLabel3.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel3.setText("Tesoros visibles");

        jLabel4.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel4.setText("Tesoros ocultos");

        niveles.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        niveles.setText("jLabel5");

        visibles.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        visibles.setText("jLabel5");

        ocultos.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        ocultos.setText("jLabel5");

        text.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        text.setText("Textooo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ocultos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(niveles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(visibles))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(niveles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(visibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ocultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel niveles;
    private javax.swing.JLabel ocultos;
    private javax.swing.JLabel text;
    private javax.swing.JLabel visibles;
    // End of variables declaration//GEN-END:variables
}
