/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.*;
/**
 *
 * @author Minim
 */
public class BadConsequenceView extends javax.swing.JPanel {
    private BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        niveles.setText("");
        ocultos.setText("");
        visibles.setText("");
    }

    public void setBadConsequence(BadConsequence b){
        badConsequenceModel = b;
        text.setText(badConsequenceModel.getText());
        niveles.setText(Integer.toString(badConsequenceModel.getLevels()));
        
        if (badConsequenceModel.getClass() == NumericBadConsequence.class){
             if(((NumericBadConsequence)badConsequenceModel).getnHiddenTreasures() == 0){
                 ocultos.setText("0");
             }
             else{
                ocultos.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getnHiddenTreasures()));
             }
             if(((NumericBadConsequence)badConsequenceModel).getnVisibleTreasures() != 0){
                visibles.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getnVisibleTreasures()));
             }
             else{
                 visibles.setText("0");
             }
        }
        else if (badConsequenceModel.getClass() == SpecificBadConsequence.class){
            String svt = "";
            
            if(((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures().isEmpty()){
                visibles.setText("empty");
            }
            else{
                for (TreasureKind tk : ((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures()){
                    svt += tk.toString() + "\n";
                }
                visibles.setText(svt);
            }
            
            if(((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures().isEmpty()){
                ocultos.setText("empty");
            }
            else{
                String sht = "";

                for (TreasureKind tk : ((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures()){
                    sht += tk.toString()+ "\n";
                }

                ocultos.setText(sht);
            }
        }
        else if(badConsequenceModel.getClass() == DeathBadConsequence.class){
            ocultos.setText("10");
            visibles.setText("10");
        }
       
        repaint();
        revalidate();
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        niveles = new javax.swing.JLabel();
        visibles = new javax.swing.JLabel();
        ocultos = new javax.swing.JLabel();
        text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel2.setText("Niveles");

        jLabel3.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel3.setText("Tesoros visibles");

        jLabel4.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel4.setText("Tesoros ocultos");

        niveles.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        niveles.setText("jLabel5");

        visibles.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        visibles.setText("jLabel5");

        ocultos.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        ocultos.setText("jLabel5");

        text.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        text.setText("Textooo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(niveles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(visibles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ocultos)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(niveles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(visibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ocultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel niveles;
    private javax.swing.JLabel ocultos;
    private javax.swing.JLabel text;
    private javax.swing.JLabel visibles;
    // End of variables declaration//GEN-END:variables
}
