/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JPanel;


/**
 *
 * @author Minim
 */
public class ExamenView extends javax.swing.JFrame {
    ArrayList <BadConsequence> malrollo = new ArrayList();
    ArrayList <Treasure> tesoros = new ArrayList();
    BadConsequence pendingModel;
    /**
     * Creates new form ExamenView
     */
    public ExamenView() {
        initComponents();
        name.setText("");
        dni.setText("");
    }
    
    private void fillBCPanel (JPanel aPanel, ArrayList<BadConsequence> aList) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
    // al panel
        for (BadConsequence b : aList) {
           BadConsequenceView aBCView = new BadConsequenceView();
           aBCView.setBadConsequence(b);
           aBCView.setVisible (true);
           aPanel.add (aBCView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
    // al panel
        for (Treasure t : aList) {
           TreasureView aTreasureView = new TreasureView();
           aTreasureView.setTreasure (t);
           aTreasureView.setVisible (true);
           aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        identificacion = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        panelMalRollo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        death = new javax.swing.JButton();
        numeric = new javax.swing.JButton();
        specific = new javax.swing.JButton();
        panelTesoros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onehand = new javax.swing.JButton();
        bothhands = new javax.swing.JButton();
        helmet = new javax.swing.JButton();
        shoes = new javax.swing.JButton();
        armor = new javax.swing.JButton();
        adjust = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adjustB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        identificacion.setText("Identificación");
        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });

        name.setText("name");

        dni.setText("dni");

        panelMalRollo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Mal rollo");
        panelMalRollo.add(jLabel1);

        death.setText("Muerte");
        death.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathActionPerformed(evt);
            }
        });

        numeric.setText("Numérico");
        numeric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numericActionPerformed(evt);
            }
        });

        specific.setText("Específicos");
        specific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificActionPerformed(evt);
            }
        });

        panelTesoros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tesoros");
        panelTesoros.add(jLabel2);

        onehand.setText("ONE HAND");
        onehand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onehandActionPerformed(evt);
            }
        });

        bothhands.setText("BOTHHANDS");
        bothhands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bothhandsActionPerformed(evt);
            }
        });

        helmet.setText("HELMET");
        helmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helmetActionPerformed(evt);
            }
        });

        shoes.setText("SHOES");
        shoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoesActionPerformed(evt);
            }
        });

        armor.setText("ARMOR");
        armor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armorActionPerformed(evt);
            }
        });

        adjust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Mal rollo por cumplir");
        adjust.add(jLabel3);

        adjustB.setText("Ajustar");
        adjustB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(identificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name)
                        .addGap(18, 18, 18)
                        .addComponent(dni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(adjustB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onehand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bothhands)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helmet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(armor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(adjust, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTesoros, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(death)
                .addGap(91, 91, 91)
                .addComponent(numeric)
                .addGap(105, 105, 105)
                .addComponent(specific)
                .addGap(266, 266, 266))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelMalRollo, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(identificacion)
                    .addComponent(name)
                    .addComponent(dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMalRollo, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specific)
                    .addComponent(numeric)
                    .addComponent(death))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTesoros, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(adjust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adjustB)
                    .addComponent(armor)
                    .addComponent(shoes)
                    .addComponent(helmet)
                    .addComponent(bothhands)
                    .addComponent(onehand))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        name.setText("Montse Rodríguez Zamorano");
        dni.setText("77391269H");
    }//GEN-LAST:event_identificacionActionPerformed

    private void specificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificActionPerformed
        BadConsequence bc;
        bc = new SpecificBadConsequence("BC3",
        0, new ArrayList(Arrays.asList(TreasureKind.ONEHAND,TreasureKind.ARMOR, TreasureKind.SHOES)),
        new ArrayList(Arrays.asList(TreasureKind.HELMET, TreasureKind.ONEHAND, TreasureKind.ONEHAND)));
        malrollo.add(bc);
        fillBCPanel(panelMalRollo,malrollo);
    }//GEN-LAST:event_specificActionPerformed

    private void bothhandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bothhandsActionPerformed
        tesoros.add(new Treasure("Tesoro", 0, TreasureKind.BOTHHANDS));
        fillTreasurePanel(panelTesoros,tesoros);
    }//GEN-LAST:event_bothhandsActionPerformed

    private void deathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathActionPerformed
        BadConsequence bc;
        bc = new DeathBadConsequence("BC1");
        malrollo.add(bc);
        fillBCPanel(panelMalRollo, malrollo);
    }//GEN-LAST:event_deathActionPerformed

    private void numericActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numericActionPerformed
        BadConsequence bc;
        bc = new NumericBadConsequence("BC2",0,3,4);
        malrollo.add(bc);
        fillBCPanel(panelMalRollo,malrollo);
    }//GEN-LAST:event_numericActionPerformed

    private void onehandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onehandActionPerformed
        tesoros.add(new Treasure("Tesoro", 0, TreasureKind.ONEHAND));
        fillTreasurePanel(panelTesoros,tesoros);
    }//GEN-LAST:event_onehandActionPerformed

    private void helmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helmetActionPerformed
        tesoros.add(new Treasure("Tesoro", 0, TreasureKind.HELMET));
        fillTreasurePanel(panelTesoros,tesoros);
    }//GEN-LAST:event_helmetActionPerformed

    private void shoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoesActionPerformed
        tesoros.add(new Treasure("Tesoro", 0, TreasureKind.SHOES));
        fillTreasurePanel(panelTesoros,tesoros);
    }//GEN-LAST:event_shoesActionPerformed

    private void armorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armorActionPerformed
        tesoros.add(new Treasure("Tesoro", 0, TreasureKind.ARMOR));
        fillTreasurePanel(panelTesoros,tesoros);
    }//GEN-LAST:event_armorActionPerformed

    private void adjustBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustBActionPerformed
        ArrayList <BadConsequence> pendingBC = new ArrayList();
        for(BadConsequence b: malrollo){
            pendingBC.add(b.adjustToFitTreasureLists(tesoros, new ArrayList()));
        }
        fillBCPanel(adjust,pendingBC);
    }//GEN-LAST:event_adjustBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adjust;
    private javax.swing.JButton adjustB;
    private javax.swing.JButton armor;
    private javax.swing.JButton bothhands;
    private javax.swing.JButton death;
    private javax.swing.JLabel dni;
    private javax.swing.JButton exit;
    private javax.swing.JButton helmet;
    private javax.swing.JButton identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel name;
    private javax.swing.JButton numeric;
    private javax.swing.JButton onehand;
    private javax.swing.JPanel panelMalRollo;
    private javax.swing.JPanel panelTesoros;
    private javax.swing.JButton shoes;
    private javax.swing.JButton specific;
    // End of variables declaration//GEN-END:variables
}
