/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Treasure;
import java.awt.Color;
/**
 *
 * @author Minim
 */
public class TreasureView extends javax.swing.JPanel {
    private Treasure treasureModel;
    private boolean selected = false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
        setOpaque(selected);
    }
    
    public boolean isSelected(){
        return selected;
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Luminari", 1, 10)); // NOI18N
        name.setText("NOMBRE");

        jLabel1.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        jLabel1.setText("BONUS");

        tipo.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        tipo.setText("TIPO DE TESORO");

        bonus.setFont(new java.awt.Font("Luminari", 0, 10)); // NOI18N
        bonus.setText("bonus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonus))
                    .addComponent(name))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bonus))
                .addGap(9, 9, 9)
                .addComponent(tipo)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        if(selected){
            setBackground(Color.orange);
            setOpaque(true);
        }
        if(!selected){
            setOpaque(false);
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked
   
    public Treasure getTreasure(){return treasureModel;}
    
    public void setTreasure(Treasure t){
        treasureModel = t;
        bonus.setText(Integer.toString(treasureModel.getBonus()));
        name.setText(treasureModel.getName());
        tipo.setText(treasureModel.getStringType(treasureModel.getType()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
